### ISSUE TITLE
Single File upload to Multiple account

### ISSUE THREAD

**Issue by tanner-envieta** [vinodc/cloud-text-editor#1]
I've been digging through the Kloudless API for a couple weeks now as somewhat of side project. I used the https://github.com/vinodc/cloud-text-editor/blob/master/editor.py  and the js authenticator library to create a test.txt file and upload it to a connected cloud account. Still using the JS library   (((Or not, for easier functionality/later additions)))  is it possible to take one file and upload it multiple accounts with one request? This would be an interesting feature that could lead to further possibilities. - Thanks in advance!

**Comment by vinodc** [comment]
@tanner-envieta This project actually ends up using the Python SDK to upload the file to the user's storage account. The JS library is only used to assist with the OAuth 2.0 process to connect the account. However, you may certainly allow the user to connect as many accounts as they would like through the Authenticator library, and upload the files to each of those accounts. Although not possible in a single request, you can perform one [upload request](https://developers.kloudless.com/docs/latest/storage#files-upload-a-file) to each account, either via the backend or the front-end (via javascript).

You may also find our [File Explorer](https://github.com/kloudless/file-explorer) JS library useful. It contains a "Saver" mode that enables you to prompt a user to browse their cloud storage accounts and choose a location to upload a file (or set of files) to. This uses purely JS on the front-end, and may be a better user experience for your use case.

Please feel free to contact us at support@kloudless.com with any other general questions on uploading files.
